/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package set.operations;

import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author youssefali
 */
public class MainWindow extends javax.swing.JFrame {
    
    ArrayList<String> universe = new ArrayList<>();
    ArrayList<ArrayList<String> > sets = new ArrayList<>();
    int maxSetsNumber = 100000;
    int maxEnteredSetNum = 0;
    
    SetOfStrings myProg = new SetOfStrings(universe, maxSetsNumber, sets);

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        for(int i=0; i<maxSetsNumber; i++){
            sets.add(new ArrayList<>());
        }
        System.out.println(sets.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        universeAdd = new javax.swing.JTextArea();
        addElements = new javax.swing.JButton();
        resetUniverse = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        setAdd = new javax.swing.JTextArea();
        resetSet = new javax.swing.JButton();
        addElementsSet = new javax.swing.JButton();
        setNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        union1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        union2 = new javax.swing.JTextField();
        getUnion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showUnion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        intersec2 = new javax.swing.JTextField();
        intersec1 = new javax.swing.JTextField();
        getIntersec = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        showIntersec = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        diff2 = new javax.swing.JTextField();
        diff1 = new javax.swing.JTextField();
        getDiff = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        showDiff = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        compSet = new javax.swing.JTextField();
        getComp = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        showComp = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        setNumberShow = new javax.swing.JTextField();
        showSetBnt = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        showSetText = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        showUniverseText = new javax.swing.JTextArea();
        showUniverse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(144, 193, 241));

        jLabel1.setBackground(new java.awt.Color(144, 193, 241));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 82, 216));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Set Operations Simulator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N

        jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        jLayeredPane1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add to the universe");

        universeAdd.setColumns(20);
        universeAdd.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        universeAdd.setRows(5);
        universeAdd.setText("Delete this line and type comma separated elements");
        universeAdd.setToolTipText("Type comma separated elements");
        universeAdd.setWrapStyleWord(true);
        universeAdd.setName(""); // NOI18N
        jScrollPane1.setViewportView(universeAdd);

        addElements.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        addElements.setText("Add elements");
        addElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addElementsActionPerformed(evt);
            }
        });

        resetUniverse.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        resetUniverse.setText("Reset universe");
        resetUniverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetUniverseActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addElements, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(resetUniverse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(resetUniverse, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(addElements, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addElements)
                    .addComponent(resetUniverse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Universe", jLayeredPane1);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add to a set");

        setAdd.setColumns(20);
        setAdd.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        setAdd.setRows(5);
        setAdd.setText("Delete this line and type comma separated elements");
        setAdd.setWrapStyleWord(true);
        setAdd.setName(""); // NOI18N
        jScrollPane3.setViewportView(setAdd);

        resetSet.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        resetSet.setText("Reset set");
        resetSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSetActionPerformed(evt);
            }
        });

        addElementsSet.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        addElementsSet.setText("Add elements");
        addElementsSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addElementsSetActionPerformed(evt);
            }
        });

        setNumber.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        setNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNumberActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel3.setText("Set number:");

        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(resetSet, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(addElementsSet, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(setNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(resetSet, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(addElementsSet, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(setNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addElementsSet)
                    .addComponent(resetSet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sets", jLayeredPane2);

        jTabbedPane2.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel7.setText("First set number:");

        union1.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        union1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                union1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel8.setText("Second set number:");

        union2.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        union2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                union2ActionPerformed(evt);
            }
        });

        getUnion.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        getUnion.setText("Get union");
        getUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getUnionActionPerformed(evt);
            }
        });

        showUnion.setColumns(20);
        showUnion.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showUnion.setRows(5);
        showUnion.setText("Union will be shown here");
        showUnion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(showUnion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(union1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(union2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getUnion, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(union1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(union2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(getUnion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Union", jPanel2);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel9.setText("First set number:");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel10.setText("Second set number:");

        intersec2.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        intersec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersec2ActionPerformed(evt);
            }
        });

        intersec1.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        intersec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersec1ActionPerformed(evt);
            }
        });

        getIntersec.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        getIntersec.setText("Get intersection");
        getIntersec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getIntersecActionPerformed(evt);
            }
        });

        showIntersec.setColumns(20);
        showIntersec.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showIntersec.setRows(5);
        showIntersec.setText("Intersection will be shown here");
        showIntersec.setWrapStyleWord(true);
        jScrollPane4.setViewportView(showIntersec);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(intersec1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(intersec2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getIntersec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intersec1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(intersec2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(getIntersec, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Intersection", jPanel3);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel11.setText("First set number:");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel12.setText("Second set number:");

        diff2.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        diff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff2ActionPerformed(evt);
            }
        });

        diff1.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        diff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff1ActionPerformed(evt);
            }
        });

        getDiff.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        getDiff.setText("Get difference");
        getDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDiffActionPerformed(evt);
            }
        });

        showDiff.setColumns(20);
        showDiff.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showDiff.setRows(5);
        showDiff.setText("Difference will be shown here");
        showDiff.setWrapStyleWord(true);
        jScrollPane5.setViewportView(showDiff);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(diff1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)
                        .addComponent(diff2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getDiff, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diff1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(diff2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(getDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Difference", jPanel4);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel13.setText("Set number:");

        compSet.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        compSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compSetActionPerformed(evt);
            }
        });

        getComp.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        getComp.setText("Get complement");
        getComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCompActionPerformed(evt);
            }
        });

        showComp.setColumns(20);
        showComp.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showComp.setRows(5);
        showComp.setText("Complement will be shown here");
        showComp.setWrapStyleWord(true);
        jScrollPane6.setViewportView(showComp);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(4, 4, 4)
                        .addComponent(compSet, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340)
                        .addComponent(getComp, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compSet, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(getComp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Complement", jPanel5);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(125, 113, 113));
        jLabel14.setText("(Type \"all\" to show all)");

        setNumberShow.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        setNumberShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNumberShowActionPerformed(evt);
            }
        });

        showSetBnt.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showSetBnt.setText("Show set");
        showSetBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSetBntActionPerformed(evt);
            }
        });

        showSetText.setColumns(20);
        showSetText.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showSetText.setRows(5);
        showSetText.setText("Set elements will be shown here");
        showSetText.setWrapStyleWord(true);
        jScrollPane7.setViewportView(showSetText);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel16.setText("Set number:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4)
                        .addComponent(setNumberShow, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(showSetBnt, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setNumberShow, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(showSetBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Show sets", jPanel6);

        showUniverseText.setColumns(20);
        showUniverseText.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showUniverseText.setRows(5);
        showUniverseText.setText("Universe elements will be shown here");
        showUniverseText.setWrapStyleWord(true);
        jScrollPane8.setViewportView(showUniverseText);

        showUniverse.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showUniverse.setText("Show universe");
        showUniverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUniverseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(showUniverse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(showUniverse, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Show universe", jPanel7);

        jLayeredPane3.setLayer(jTabbedPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Operations", jLayeredPane3);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Made by: Youssef Ali Hassan, 2017");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addElementsActionPerformed
        String uniString = universeAdd.getText();
        String[] uniArr = uniString.split("\\s*,\\s*");
        for(int i=0; i<uniArr.length; i++){
            String ele = uniArr[i];
            boolean dup = false;
            for(int j=0; j<universe.size(); j++){
                if(ele.equals(universe.get(j))){
                    dup = true;
                    break;
                }
            }
            if(!dup){
                System.out.println(ele);
                universe.add(ele);
            }
        }
        System.out.println(universe);
        myProg = new SetOfStrings(universe, maxSetsNumber, sets);
    }//GEN-LAST:event_addElementsActionPerformed

    private void resetUniverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetUniverseActionPerformed
        universe = new ArrayList<>();
        myProg = new SetOfStrings(universe, maxSetsNumber, sets);
    }//GEN-LAST:event_resetUniverseActionPerformed

    private void resetSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSetActionPerformed
        if(setNumber.getText().equals(""))
            return;
        int enteredSetNumber = Integer.parseInt(setNumber.getText());
        maxEnteredSetNum = Math.max(maxEnteredSetNum, enteredSetNumber);
        ArrayList<String> empty = new ArrayList<>();
        sets.set(enteredSetNumber, empty);
        
        myProg = new SetOfStrings(universe, maxSetsNumber, sets);
    }//GEN-LAST:event_resetSetActionPerformed

    private void addElementsSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addElementsSetActionPerformed
        if(setNumber.getText().equals(""))
            return;
        int enteredSetNumber = Integer.parseInt(setNumber.getText());
        maxEnteredSetNum = Math.max(maxEnteredSetNum, enteredSetNumber);
        String[] setArr = setAdd.getText().split("\\s*,\\s*");
        for(String ele : setArr){
            boolean dup = false;
            boolean inUniv = false;
            for(int j=0; j<sets.get(enteredSetNumber).size(); j++){
                if(ele.equals(sets.get(enteredSetNumber).get(j))){
                    dup = true;
                    break;
                }
            }
            for(int i=0; i<universe.size(); i++){
                System.out.println(universe.get(i) + " " + ele);
                if(universe.get(i).equals(ele)){
                    inUniv = true;
                    break;
                }
            }
            System.out.println(inUniv);
            if(!dup && inUniv){
                System.out.println(ele);
                sets.get(enteredSetNumber).add(ele);
            }
        }
        System.out.println(sets);
        myProg = new SetOfStrings(universe, maxSetsNumber, sets);
    }//GEN-LAST:event_addElementsSetActionPerformed

    private void setNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setNumberActionPerformed

    private void union1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_union1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_union1ActionPerformed

    private void union2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_union2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_union2ActionPerformed

    private void intersec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intersec2ActionPerformed

    private void intersec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intersec1ActionPerformed

    private void diff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diff2ActionPerformed

    private void diff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diff1ActionPerformed

    private void compSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compSetActionPerformed

    private void setNumberShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNumberShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setNumberShowActionPerformed

    private void showUniverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUniverseActionPerformed
        StringBuilder sb = new StringBuilder();
        sb.append("{ ");
        for(int i=0; i<myProg.getUniverse().size(); i++){
            sb.append(myProg.getUniverse().get(i));
            if(i<myProg.getUniverse().size()-1)
                sb.append(", ");
        }
        sb.append(" }");
        showUniverseText.setText(sb.toString());
    }//GEN-LAST:event_showUniverseActionPerformed

    private void showSetBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSetBntActionPerformed
        if(setNumberShow.getText().equals(""))
            return;
        if(setNumberShow.getText().equalsIgnoreCase("all") || setNumberShow.getText().equalsIgnoreCase("\"all\"")){
            // print all sets
            int cnt = -1;
            StringBuilder sb = new StringBuilder();
            for(ArrayList<String> set : myProg.getSets()){
                cnt++;
                if(set.isEmpty())
                    continue;
                sb.append("Set #" + cnt + " : ");
                sb.append("{ ");
                for(int i=0; i<set.size(); i++){
                    sb.append(set.get(i));
                    if(i<set.size()-1)
                        sb.append(", ");
                }
                sb.append(" }\n");
                if(cnt == maxEnteredSetNum)
                    break;
            }
            showSetText.setText(sb.toString());
            return;
        }
        int enteredSetNumber = Integer.parseInt(setNumberShow.getText());
        StringBuilder sb = new StringBuilder();
        sb.append("{ ");
        for(int i=0; i<myProg.getSets().get(enteredSetNumber).size(); i++){
            sb.append(myProg.getSets().get(enteredSetNumber).get(i));
            if(i<myProg.getSets().get(enteredSetNumber).size()-1)
                sb.append(", ");
        }
        sb.append(" }");
        showSetText.setText(sb.toString());
    }//GEN-LAST:event_showSetBntActionPerformed

    private void getUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUnionActionPerformed
        if(union1.getText().equals("") || union2.getText().equals(""))
            return;
        ArrayList<String> union = myProg.union(Integer.parseInt(union1.getText()), Integer.parseInt(union2.getText()));
        Collections.sort(union);
        StringBuilder sb = new StringBuilder();
        sb.append("{ ");
        for(int i=0; i<union.size(); i++){
            sb.append(union.get(i));
            if(i<union.size()-1)
                sb.append(", ");
        }
        sb.append(" }");
        showUnion.setText(sb.toString());
    }//GEN-LAST:event_getUnionActionPerformed

    private void getIntersecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getIntersecActionPerformed
        if(intersec1.getText().equals("") || intersec2.getText().equals(""))
            return;
        ArrayList<String> intersec = myProg.intersect(Integer.parseInt(intersec1.getText()), Integer.parseInt(intersec2.getText()));
        Collections.sort(intersec);
        StringBuilder sb = new StringBuilder();
        sb.append("{ ");
        for(int i=0; i<intersec.size(); i++){
            sb.append(intersec.get(i));
            if(i<intersec.size()-1)
                sb.append(", ");
        }
        sb.append(" }");
        showIntersec.setText(sb.toString());
    }//GEN-LAST:event_getIntersecActionPerformed

    private void getCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCompActionPerformed
        if(compSet.getText().equals(""))
            return;
        ArrayList<String> comp = myProg.complement(Integer.parseInt(compSet.getText()));
        Collections.sort(comp);
        StringBuilder sb = new StringBuilder();
        sb.append("{ ");
        for(int i=0; i<comp.size(); i++){
            sb.append(comp.get(i));
            if(i<comp.size()-1)
                sb.append(", ");
        }
        sb.append(" }");
        showComp.setText(sb.toString());
    }//GEN-LAST:event_getCompActionPerformed

    private void getDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDiffActionPerformed
        if(diff1.getText().equals("") || diff2.getText().equals(""))
            return;
        ArrayList<String> diff = myProg.difference(Integer.parseInt(diff1.getText()), Integer.parseInt(diff2.getText()));
        Collections.sort(diff);
        StringBuilder sb = new StringBuilder();
        sb.append("{ ");
        for(int i=0; i<diff.size(); i++){
            sb.append(diff.get(i));
            if(i<diff.size()-1)
                sb.append(", ");
        }
        sb.append(" }");
        showDiff.setText(sb.toString());
    }//GEN-LAST:event_getDiffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addElements;
    private javax.swing.JButton addElementsSet;
    private javax.swing.JTextField compSet;
    private javax.swing.JTextField diff1;
    private javax.swing.JTextField diff2;
    private javax.swing.JButton getComp;
    private javax.swing.JButton getDiff;
    private javax.swing.JButton getIntersec;
    private javax.swing.JButton getUnion;
    private javax.swing.JTextField intersec1;
    private javax.swing.JTextField intersec2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton resetSet;
    private javax.swing.JButton resetUniverse;
    private javax.swing.JTextArea setAdd;
    private javax.swing.JTextField setNumber;
    private javax.swing.JTextField setNumberShow;
    private javax.swing.JTextArea showComp;
    private javax.swing.JTextArea showDiff;
    private javax.swing.JTextArea showIntersec;
    private javax.swing.JButton showSetBnt;
    private javax.swing.JTextArea showSetText;
    private javax.swing.JTextArea showUnion;
    private javax.swing.JButton showUniverse;
    private javax.swing.JTextArea showUniverseText;
    private javax.swing.JTextField union1;
    private javax.swing.JTextField union2;
    private javax.swing.JTextArea universeAdd;
    // End of variables declaration//GEN-END:variables
}
